### ISSUE TITLE
[Request] CastAR integration for VOX Framework?

### ISSUE THREAD

**Issue by HeadClot** [AlwaysGeeky/Vox#10]
Hey, 
Would it be possible to get a [CASTAR](http://castar.com/) integration for VOX?

Just curious here as I would like to get some sort of augmented reality "Dungeon Master" mode going for my game that going to be based on this framework.

I can get you in contact with the right people to get you access to the SDK.

Let me know,
HeadClot

**Comment by AlwaysGeeky** [comment]
Hi, thanks for your interest and request... as of right not I don't have any imeediate plans for integrating a VR sdk to my voxel engine, since it is still very early days for the voxel engine.

But at some point in the future it could be a possibility, I just have far too much else on my TODO for the project at the moment.

Also there is nothing stopping anyone else who wants to fork the code and integrate that SDK that you mentioned. that is the benefit of github, if anyone wants or is able to, they are free to do this integration work.

Also you idea of a VR dungeon Master game sounds quite interesting, I would be very interested to see how this turns out.

Cheers.

**Comment by AlwaysGeeky** [comment]
I'm gonna mark this as closed because It is highly unlikely that I will be implementing this request in the near future, but feel free to carry on discussions.
