### ISSUE TITLE
crash on linux when character dies

### ISSUE THREAD

**Issue by lostcoder** [AlwaysGeeky/Vox#170]
The game tries to load the Tombstone[1-2].item files but fails due to case.  The files are "Tombstone" while the game tries to load "tombstone".  The actual crash is due to an incorect check in item.cpp:242. It checks for m_pVoxelItem != NULL which is always true. I think you wanted to test IsLoaded().

**Comment by AlwaysGeeky** [comment]
Thanks for this bug, I just fixed this in the commit: https://github.com/AlwaysGeeky/Vox/commit/83e74e2460f9af04aea4b03d6dec83d5aa15263f

**Comment by StepDevelop** [comment]
Vox is a wonderful project! I thank you for having released "Vox" as Open
Source. I'm Italian, 38, a computer science enthusiast since 1984! is a
model 3d artist, know the languages:

Python
Lua
HTML5 (CSS3, Javascript included)

I'm not a C ++ programmer :(

I can create graphic content for Vox, documentation, official web site of
the project (if you want it), with your permission I would like to work for
your project, Vox interests me very much.

Thank you very much, and continues to develop Vox! you did a great job!

2016-04-25 22:30 GMT+02:00 Steve <notifications@github.com>:

**Comment by AlwaysGeeky** [comment]
Hey @StepDevelop yes this is totally fine, that is the whole point of Vox open source, so that other people can contribute and help out with these sort of tasks and work.

Please let me know what you would like to work on and what interests you.

Thanks!
