### ISSUE TITLE
Running Vox binary on OSX results in segfault - "Can't load 'media/config/options.ini'"

### ISSUE THREAD

**Issue by Polyrhythm** [AlwaysGeeky/Vox#174]
Hey! I've managed to get a build working on OSX. It successfully builds/links and creates `Vox`. I did all of this in a `build/` dir and when I try to `./Vox` or even move it to the root dir and `./Vox` I get a segfault. If I `open Vox` I get:

```
Can't load 'media/config/settings.ini'
Can't load 'media/config/options.ini'
[1]    25605 segmentation fault  /Users/ryanjones/Development/cpp/Vox/build/source/Vox
```

**Comment by AlwaysGeeky** [comment]
That is strange, the files exist and you can clearly see them in the repo, I would guess that something about the pathing is incorrect on the OSX. Maybe the working directory for the vox executable isnt correctly set?

Sorry I cant help too much I don't have OSX dev setup easily atm.

But thanks for your assistance!

**Comment by jomstead** [comment]
I have the same problem when compiling and running using Visual Studio 2015.  I open the included project .sln file, complile the project, and when it runs I get:
Can't load 'media/config/settings.ini'
Can't load 'media/config/options.ini'
I had to change the paths to "../../media/config/settings.ini"...
This was because the project sln files were in a directory buried a few directories deep and when you use Visual Studio 2015 and try to run the code it uses that directory as the directory to look for "media/config/settings.ini".

Maybe the same thing is happening for you?  Or maybe I'm doing something wrong when loading the project?

**Comment by AlwaysGeeky** [comment]
@jomstead no, you need to set the debugging options "working directory" in visual studio, if you want to run the executable from within visual studio itself. You need to set the debugging option to "../.."

This is explained in the readme file: https://github.com/AlwaysGeeky/Vox/blob/master/README.md under the section **Running**.

**Comment by jomstead** [comment]
Thanks for the quick reply.  I figured it was something had set up wrong.

**Comment by Polyrhythm** [comment]
I've discovered the problem is that you need to get the full path on OSX as relative paths don't work. To get around it for now I've hardcoded the path so I can continue traipsing into further build issues to see if I can get it running.

**Comment by AlwaysGeeky** [comment]
Hmmm really? that is very curious, there must be some other way for this to work on OSX, since there is no way that every executable has to have full paths hard coded into the code to work.

I'm not an expert on OSX development so cant really offer too much assistance, but maybe you can do some investigation on this and figure out a solution?

Thank you :)

**Comment by Polyrhythm** [comment]
Yeah, I'm slowly working my way through stuff. It would be neat if there was an irc room or something to bounce ideas off of instead of making little issues for every problem I encounter

**Comment by AlwaysGeeky** [comment]
You can join and chat in the gitter chat room: https://gitter.im/AlwaysGeeky/Vox

**Comment by AlwaysGeeky** [comment]
Also, feel free to add a project file for OSX in the appropriate folder:

/Vox/projects/osx (or mac)

And then anyone else developing on Mac can also use this.

Btw, what IDE do you use, xcode?

**Comment by Polyrhythm** [comment]
I'm not using an IDE at all! Just emacs and command line. I might start on the IDE stuff if I can get this bad boy running. Thanks for the heads up on the `projects` dir.

**Comment by AlwaysGeeky** [comment]
I'm going to close this issue now, since the original BUG isn't an issue.
