### ISSUE TITLE
Question about Vox Game

### ISSUE THREAD

**Issue by bsparks** [AlwaysGeeky/Vox#27]
I bought the alpha for Vox a long time ago on Desura. Is this the source for that or have you removed some things for the OS version? Should any/all of the media from the game work on this engine?

**Comment by AlwaysGeeky** [comment]
Hey, thanks for the question.

Well actually the OS version is the updated code and all of the new stuff in Vox that was re-written and done from scratch... so unfortunately not much content from the current 'public' version of Vox (Desura or Steam) will be compatible since so much of the code and filesystems have changed.

The plan is to make the Open Source version here mostly code and engine and keep the media and content to the Released versions of Vox.. but essentially they will be very closely aligned.

Also the OS code is a way for other people to see how the game is coded and also suggest or add to it, and also have a say on the features and gameplay that goes into the game.

Right now I am essentially moving a lot of the new gameplay and functionality that I have coded for the unreleased version of Vox, over to github and making sure it is solid, then a new version of the Vox game (With all game content and media) will be pushed to the output sources for players to receive.

Hope that answers you questions.

**Comment by bsparks** [comment]
yes, thanks for the answers
