### ISSUE TITLE
snprintf only available in Visual studio 2015?

### ISSUE THREAD

**Issue by Daddatt** [AlwaysGeeky/Vox#41]
I tried building with Visual studio 2013 but got lots of error messages regarding 'snprintf'
It looks like its only available in Visual studio 2015?

Just thought I'd let you know.

PS. I'm looking at possibly using Vox for my own game, I'm currently looking through the code trying to understand how it does things, thanks for creating it and sharing it.

**Comment by AlwaysGeeky** [comment]
Hey @Daddatt, thanks for reporting this.

I have actually just fixed this issue in VS2012 and VS2013... I converted the snprintf instances to use sprintf instead, since I use this is other places also, I know it is not exactly as safe as snprintf... but I wont this to be compatible on all project versions.

Let me know how this works out for you with the latest code.

Cheers.
